((nil . ((company-clang-arguments
          . ("-I/home/dipu/my/pico/kbd/build/generated/pico_base"

             "-I/home/dipu/my/pico/kbd/pico-sdk/src/common/boot_picoboot/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/common/boot_uf2/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/common/pico_base/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/common/pico_binary_info/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/common/pico_bit_ops/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/common/pico_divider/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/common/pico_stdlib/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/common/pico_sync/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/common/pico_time/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/common/pico_usb_reset_interface/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/common/pico_util/include"

             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2040/hardware_regs/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2040/hardware_structs/include"

             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_adc/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_base/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_claim/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_clocks/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_divider/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_dma/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_exception/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_flash/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_gpio/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_i2c/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_interp/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_irq/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_pio/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_pll/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_pwm/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_resets/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_rtc/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_spi/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_sync/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_timer/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_uart/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_vreg/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_watchdog/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_xosc/include"

             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_bit_ops/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_bootrom/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_bootsel_via_double_reset/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_cxx_options/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_cyw43_arch/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_divider/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_double/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_fix/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_float/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_int64_ops/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_lwip/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_malloc/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_mem_ops/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_multicore/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_platform/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_printf/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_runtime/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_standard_link/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_stdio/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_stdio_semihosting/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_stdio_uart/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_stdio_usb/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_stdlib/include"
             "-I/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_unique_id/include"

             ;; alternate versions for host build (PICO_PLATFORM=host)
             ;; "-I/home/dipu/my/pico/kbd/pico-sdk/src/host/hardware_divider/include"
             ;; "-I/home/dipu/my/pico/kbd/pico-sdk/src/host/hardware_gpio/include"
             ;; "-I/home/dipu/my/pico/kbd/pico-sdk/src/host/hardware_sync/include"
             ;; "-I/home/dipu/my/pico/kbd/pico-sdk/src/host/hardware_timer/include"
             ;; "-I/home/dipu/my/pico/kbd/pico-sdk/src/host/hardware_uart/include"
             ;; "-I/home/dipu/my/pico/kbd/pico-sdk/src/host/pico_bit_ops/include"
             ;; "-I/home/dipu/my/pico/kbd/pico-sdk/src/host/pico_divider/include"
             ;; "-I/home/dipu/my/pico/kbd/pico-sdk/src/host/pico_multicore/include"
             ;; "-I/home/dipu/my/pico/kbd/pico-sdk/src/host/pico_platform/include"
             ;; "-I/home/dipu/my/pico/kbd/pico-sdk/src/host/pico_printf/include"
             ;; "-I/home/dipu/my/pico/kbd/pico-sdk/src/host/pico_stdio/include"
             ;; "-I/home/dipu/my/pico/kbd/pico-sdk/src/host/pico_stdlib/include"

             ))
         (flycheck-clang-include-path
          . ("/home/dipu/my/pico/kbd/build/generated/pico_base"

             "/home/dipu/my/pico/kbd/pico-sdk/src/common/boot_picoboot/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/common/boot_uf2/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/common/pico_base/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/common/pico_binary_info/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/common/pico_bit_ops/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/common/pico_divider/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/common/pico_stdlib/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/common/pico_sync/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/common/pico_time/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/common/pico_usb_reset_interface/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/common/pico_util/include"

             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2040/hardware_regs/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2040/hardware_structs/include"

             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_adc/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_base/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_claim/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_clocks/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_divider/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_dma/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_exception/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_flash/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_gpio/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_i2c/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_interp/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_irq/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_pio/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_pll/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_pwm/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_resets/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_rtc/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_spi/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_sync/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_timer/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_uart/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_vreg/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_watchdog/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/hardware_xosc/include"

             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_bit_ops/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_bootrom/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_bootsel_via_double_reset/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_cxx_options/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_cyw43_arch/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_divider/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_double/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_fix/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_float/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_int64_ops/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_lwip/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_malloc/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_mem_ops/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_multicore/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_platform/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_printf/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_runtime/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_standard_link/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_stdio/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_stdio_semihosting/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_stdio_uart/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_stdio_usb/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_stdlib/include"
             "/home/dipu/my/pico/kbd/pico-sdk/src/rp2_common/pico_unique_id/include"

             ;; alternate versions for host build (PICO_PLATFORM=host)
             ;; "/home/dipu/my/pico/kbd/pico-sdk/src/host/hardware_divider/include"
             ;; "/home/dipu/my/pico/kbd/pico-sdk/src/host/hardware_gpio/include"
             ;; "/home/dipu/my/pico/kbd/pico-sdk/src/host/hardware_sync/include"
             ;; "/home/dipu/my/pico/kbd/pico-sdk/src/host/hardware_timer/include"
             ;; "/home/dipu/my/pico/kbd/pico-sdk/src/host/hardware_uart/include"
             ;; "/home/dipu/my/pico/kbd/pico-sdk/src/host/pico_bit_ops/include"
             ;; "/home/dipu/my/pico/kbd/pico-sdk/src/host/pico_divider/include"
             ;; "/home/dipu/my/pico/kbd/pico-sdk/src/host/pico_multicore/include"
             ;; "/home/dipu/my/pico/kbd/pico-sdk/src/host/pico_platform/include"
             ;; "/home/dipu/my/pico/kbd/pico-sdk/src/host/pico_printf/include"
             ;; "/home/dipu/my/pico/kbd/pico-sdk/src/host/pico_stdio/include"
             ;; "/home/dipu/my/pico/kbd/pico-sdk/src/host/pico_stdlib/include"

             )))))
